frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\BadDomain;
use common\models\Click;
use common\models\Pagination;
use yii\helpers\Json;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    protected const PER_PAGE_LIMITS = [10, 25, 50, 100];
    protected const PER_PAGE_DEFAULT = 10;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $request = \Yii::$app->getRequest()->getIsGet() ? \Yii::$app->getRequest()->get() : \Yii::$app->getRequest()->post();

        $query = Click::find();

        // ищем
        if (!empty($request['q'])) {
            // понятно, что не гоже запросы с таким условием писать - сделал только для
            $query->where(['LIKE', 'id', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'ua', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'ip', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'ref', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'param1', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'param2', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'error', "{$request['q']}%", false])
                ->orWhere(['LIKE', 'bad_domain', "{$request['q']}%", false]);
        }

        // сортируем
        if (!empty($request['sort'])) {
            $click = new Click();
            foreach ($request['sort'] as $sortParam => $sortValue) {
                if ($click->hasAttribute($sortParam)) {
                    $query->addOrderBy([$sortParam => $sortValue === 'desc' ? SORT_DESC : SORT_ASC]);
                }
            }
        }

        // выставляем лимиты
        $pages = new Pagination([
            'totalCount' => $query->count('id'),
            'pageSize'   => isset($request['per-page']) && in_array($request['per-page'], self::PER_PAGE_LIMITS) ? $request['per-page'] : self::PER_PAGE_DEFAULT,
        ]);
        $query = $query->limit($pages->limit)->offset($pages->offset);

        return \Yii::$app->getRequest()->getIsAjax() ?
            Json::encode(['html' => $this->renderPartial('/site/click-form-table', ['clicks' => $query->all(), 'pages' => $pages, 'params' => $request])]) :
            $this->render('index', ['clicks' => $query->all(), 'pages' => $pages, 'params' => $request]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionBadDomains()
    {
        $request = \Yii::$app->getRequest();
        $badDomain = new BadDomain();
        if ($request->getIsPost()) {
            $badDomain->setScenario(BadDomain::SCENARIO_CREATE);
            $badDomain->setAttributes($request->post());
            $badDomain->save();
        }

        $q = BadDomain::find();
        $pages = new Pagination([
            'totalCount' => $q->count('id'),
            'pageSize'   => 20,
        ]);
        $q = $q->orderBy(['id' => SORT_DESC])->limit($pages->limit)->offset($pages->offset);

        return $this->render('bad-domains', ['badDomains' => $q->all(), 'pages' => $pages, 'newDomain' => $badDomain]);
    }

    public function actionMakeClick()
    {
        $str1 = \Yii::$app->getSecurity()->generateRandomString(mt_rand(4, 8));
        $str2 = \Yii::$app->getSecurity()->generateRandomString(mt_rand(4, 8));

        return $this->redirect(['/click', 'param1' => $str1, 'param2' => $str2]);
    }

    public function actionClearClick()
    {
        Click::getDb()->createCommand()->truncateTable(Click::tableName())->execute();

        return $this->redirect(['/']);
    }

    public function actionTest()
    {
        //        set_time_limit(0);
        //        ini_set('memory_limit', '500M');
        //
        //        $start = 0;
        //        $end = 3000000;
        //        $refsArr = [
        //            'http://localhost/',
        //            'http://google.com/',
        //            'http://yandex.ru/',
        //            'http://mail.ru',
        //            'http://yahoo.com',
        //            'http://obj.ru',
        //        ];
        //
        //        $columns = ['id', 'ua', 'ip', 'ref', 'param1', 'param2'];
        //        for ($i = $start; $i < $end; ++$i)
        //        {
        //            $data[] = [
        //                hash('sha3-512', $i . microtime(true)),
        //                'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36',
        //                '127.0.0.1',
        //                $refsArr[mt_rand(0, count($refsArr) - 1)],
        //                \Yii::$app->getSecurity()->generateRandomString(mt_rand(4, 10)),
        //                \Yii::$app->getSecurity()->generateRandomString(mt_rand(4, 10)),
        //            ];
        //
        //            if ($i % 1000 === 0) {
        //                Click::getDb()->createCommand()->batchInsert(Click::tableName(), $columns, $data)->execute();
        //                $data = [];
        //            }
        //        }
        //
        //        return $this->redirect(['/']);
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
$this->title = 'Test case';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Home',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'make click', 'url' => ['/site/make-click']],
        ['label' => 'clear clicks', 'url' => ['/site/clear-click']],
        ['label' => 'click list', 'url' => ['/site/index']],
        ['label' => 'bad_domains list', 'url' => ['/site/bad-domains']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>